/*
 * DWIN_Adress.h
 *
 *  Created on: Jan 23, 2025
 *      Author: Step
 */

#ifndef INC_DWIN_ADRESS_H_
#define INC_DWIN_ADRESS_H_

#include "main.h"


#define STM32_OTA_BEGIN_ADR 100


/*---------------------------- SAYFALAR ------------------------------*/

#define DW_ARIZA_PAGE_ADR					97
#define DW_PISIRME_PAGE_ADR					2

#define DW_CIHAZ_TEST_PAGE_ADR				100

#define DW_PISIRME_DUZEN_PAGE1_ADR			38
#define DW_PISIRME_DUZEN_PAGE2_ADR			37
#define DW_PISIRME_DUZEN_PAGE3_ADR			35
#define DW_PISIRME_DUZEN_PAGE4_ADR			32

#define DW_EMPTY_PAGE_NUM					7

#define DW_PAGE_MANUEL_BUHARVAR_TEKTC_ADR	94
#define DW_PAGE_MANUEL_BUHARVAR_CIFTTC_ADR	2
#define DW_PAGE_MANUEL_BUHARYOK_CIFTTC_ADR	96
#define DW_PAGE_MANUEL_BUHARYOK_TEKTC_ADR	95

#define DW_PAGE_RECETE_BUHARVAR_TEKTC_ADR	84
#define DW_PAGE_RECETE_BUHARYOK_TEKTC_ADR	85
#define DW_PAGE_RECETE_BUHARVAR_CIFTTC_ADR	82
#define DW_PAGE_RECETE_BUHARYOK_CIFTTC_ADR	83

#define DW_RECETE_PISIRME_PAGE_ADR			82
#define DW_AYARLAR_PAGE_ADR					86
#define DW_ANA_PAGE_ADR						10

#define DW_CIHAZ_TEST_PAGE_PSW				9905

#define DW_LOADING_PAGE_ADR					0xF100
#define DW_EKRAN_PROG_CHECK_ADR				0x7995



#define DW_EKRAN_PROG_MASTER_VAL			1
#define DW_EKRAN_PROG_CONV_VAL				2

/*---------------------------- TEST SAYFASI ------------------------------*/

#define DW_TEST_TC1_ADR				0x2900
#define DW_TEST_TC2_ADR				0x2901
#define DW_TEST_TC3_ADR				0x2902

#define DW_TEST_K1_ADR 				0x290B
#define DW_TEST_BUZZER_ADR 			0x291C

#define DW_TEST_HEPSINIAC_ADR 		0x291D
#define DW_TEST_HEPSINIKAPAT_ADR 	0x291E

#define DW_TEST_1KHZ_ADR			0x291F
#define DW_TEST_2KHZ_ADR			0x2920
#define DW_TEST_3KHZ_ADR			0x2921
#define DW_TEST_4KHZ_ADR			0x2922

#define DW_TEST_OUT2_3V_ADR			0x2923
#define DW_TEST_OUT2_6V_ADR			0x2924
#define DW_TEST_OUT2_9V_ADR			0x2925

#define DW_TEST_OUT1_5V_ADR			0x2926
#define DW_TEST_OUT1_10V_ADR		0x2927
#define DW_TEST_OUT1_15V_ADR		0x2928

#define DW_TEST_EXIT_ADR			0x2929

/*--------------------------------- MODE INFO -------------------------------*/

#define REG_DW_MODE_INFO_ADR			0x2000

#define DW_ANA_SAYFA_ENTER				0
#define DW_MANUEL_MODE_ENTER			1
#define DW_RECETE_SAYFA_ENTER			2
#define DW_RECETE_PISIRME_SAYFA_ENTER	3
#define DW_RECETE_DUZEN_SAYFA_ENTER		4
#define DW_OTOMATIK_ACMA_SAYFA_ENTER	5
#define DW_CIHAZ_TEST_SAYFA_ENTER		6

/*---------------------------- MANUEL SAYFASI ------------------------------*/

#define DW_MANUEL_MOD_GIRIS_ADR			0x2000

#define DW_ILK_KULLANILAN_ADR			DW_UST_SICAKLIK_SET_ADR

#define DW_UST_SICAKLIK_SET_ADR			0x1000
#define DW_ALT_SICAKLIK_SET_ADR			0x1002
#define DW_PISIRME_SURESI_ADR			0x100A
#define DW_PISIRME_SURESI_SN_ADR		0x100E
#define DW_BUHAR_SURESI_ADR				0x100C
#define DW_TMP112_ADR					0x100F
#define DW_UST_SICAKLIK_ADR				0x1010
#define DW_ALT_SICAKLIK_ADR				0x1011
#define DW_PISIRME_BASLATMA_ADR			0x1012
#define DW_PISIRME_SONLANDIRMA_ADR		0x1014
#define DW_BUHAR_HAZIRLAMA_ADR			0x1015
#define DW_BUHAR_PUSKURTME_ADR			0x1018
#define DW_LAMBA_ADR					0x1019
#define DW_TURBO_ADR					0x101A
#define DW_PISIRME_ALARM_SUSTURMA_ADR	0x108A


/*------------------------------- ANIMSAYON ADDRESS  --------------------------------*/

#define DW_UST_SICAKLIK_ANIM			0x101C
#define DW_ALT_SICAKLIK_ANIM			0x101E
#define DW_SURE_SONU_ALARM_ANIM_ADR		0x1020
//#define DW_UST_ON_ANIM					0x1020
//#define DW_UST_ARKA_ANIM				0x1022
//#define DW_ALT_ANIM						0x1024
#define DW_BUHAR_HAZIR_ANIM				0x1016

/*---------------------------- ORTAK AYARLAMA SAYFASI	 ------------------------------*/

#define DW_UST_SICAKLIK_SET_ORT_ADR		0x155B
#define DW_ALT_SICAKLIK_SET_ORT_ADR		0x155D
#define DW_UST_ON_SET_ORT_ADR			0x155F
#define DW_UST_ARKA_SET_ORT_ADR			0x1561
#define DW_ALT_SET_ORT_ADR				0x1563
#define DW_PISIRME_SURESI_ORT_ADR		0x1565
#define DW_BUHAR_SURESI_ORT_ADR			0x1567
#define DW_UST_SICAKLIK_SET_ONAY_ADR	0x1569
#define DW_ALT_SICAKLIK_SET_ONAY_ADR	0x156A
#define DW_UST_ON_SET_ONAY_ADR			0x156B
#define DW_UST_ARKA_SET_ONAY_ADR		0x156C
#define DW_ALT_SET_ONAY_ADR				0x156D
#define DW_PISIRME_SURESI_SET_ONAY_ADR	0x156E
#define DW_BUHAR_SURESI_SET_ONAY_ADR	0x156F

/*---------------------------- PARAMETRELER SAYFASI	 ------------------------------*/

#define DW_FW_VERSION_ADR				0x17E0

#define DW_PARAMETRE_PAGE_ADR			0x17A8
#define DW_PARAMETRE_EXIT_PAGE_ADR		0x17FA
#define DW_PARAMETRE_DEFAULT_PSW		7251

#define DW_PARAM_LAMBA_SURESI_ADR		0x17AA
#define DW_PARAM_BUTTON_SOUND_ADR		0x17AC
#define DW_PARAM_ALARM_ADR				0x17AE
#define DW_PARAM_DIL_ADR				0x17B0
#define DW_PARAM_PSW_ADR				0x17B2
#define DW_PARAM_BUHAR_ACTIVE_ADR		0x17B4
#define DW_PARAM_BUHAR_SENSOR_TYPE_ADR	0x17B6
#define DW_PARAM_BUHAR_MAX_SET_ADR		0x17B8
#define DW_PARAM_BUHAR_HAZIR_SICAK_ADR	0x17BA
#define DW_PARAM_BUHAR_UST_HIS_ADR		0x17BC
#define DW_PARAM_BUHAR_ALT_HIS_ADR		0x17BE
#define DW_PARAM_CIHAZ_TYPE_ADR			0x17C0
#define DW_PARAM_LOGO_ADR				0x17C2
#define DW_PARAM_LOGO_CNT_ADR			0x177C
#define DW_PARAM_TERMOKUPL_TYPE_ADR		0x17FD
#define DW_FARBRIKA_AYAR_PARAM_ADR		0x17FC



#define DW_K_TYPE_TERMOKUP_VAL			1
#define DW_J_TYPE_TERMOKUP_VAL			0

#define DW_BUHAR_SENSOR_KUPL_VAL		0
#define DW_BUHAR_SENSOR_TAT_VAL			1

/*---------------------------- BLUETOOTH SAYFASI	 ------------------------------*/

#define DW_BLE_NAME_START_ADR			0x17C4
#define DW_BLE_PSW_START_ADR			0x17DE
#define DW_QR_CODE_ADR					0x75BB
#define DW_BLE_IKON_ADR					0x177B

/*---------------------------- DIL ------------------------------*/

#define DW_DIL_SABIT_YAZI_ADR			0x843A

#define DW_DIL_TURKCE_VAL 				0
#define DW_DIL_INGILIZCE_VAL 			1
#define DW_DIL_RUSCA_VAL 				2
#define DW_DIL_ALMANCA_VAL 				3

/*---------------------------- ARIZA ALARM SAYFASI	 ------------------------------*/

#define DW_TC1_ARIZA_ADR				0x178E
#define DW_TC2_ARIZA_ADR				0x178F
#define DW_TC3_ARIZA_ADR				0x1790
#define DW_MCP9700_ARIZA_ADR			0x1791
#define DW_EEPROM_ARIZA_ADR				0x1792
#define DW_ASIRI_SICAKLIK_ARIZA_ADR		0x1793
#define DW_ARIZA_ALARM_SUSTURMA_ADR		0x1794

/*--------------------------------- RECETELER -----------------------------------*/

#define DW_RECETE_SAYFA_ENTER_ADR		0x2800
#define DW_RECETE_CIKIS_CMD				0x107F
#define DW_RECETE_AMOUNT				100
#define DW_RECETE_ISIM_SIZE				10
#define DW_RECETE_RESIM_ILK_ADR			0x10FB
#define DW_RECETE_ISIM_ILK_ADR			0x115F

#define DW_RECETE_ILK_ADR				0x1097
#define DW_RECETE_SON_ADR				0x10FA

#define DW_RECETE_UST_SICAKLIK_SET_ADR	0x1039
#define DW_RECETE_ALT_SICAKLIK_SET_ADR	0x103B
#define DW_RECETE_UST_ON_SET_ADR		0x103D

#define DW_RECETE_DUZ_RESIM_ADR			0x1071
#define DW_RECETE_DUZ_NUM_ADR			0x1072
#define DW_RECETE_DUZ_ISIM_ADR			0x1073
#define DW_RECETE_DUZ_ADIM_SAY_ADR		0x107E
#define DW_RECETE_DUZ_UST_SIC_SET_ADR	0x1039

#define DW_RECETE_PISIR_UST_SIC_SET_ADR	0x1000
#define DW_RECETE_PISIR_SURE_ADR		0x100A

#define DW_RECETE_PISIRME_CMD			1
#define DW_RECETE_DUZENLEME_CMD			2

#define DW_RECETE_A1_ANIM_ADR			0x1082
#define DW_RECETE_A2_ANIM_ADR			0x1084
#define DW_RECETE_A3_ANIM_ADR			0x1086
#define DW_RECETE_A4_ANIM_ADR			0x1088

#define APP_RECETE_ILK_ADR				0x2328
#define APP_RECETE_LENGTH				35
#define APP_RECETE_PISIRME_START_ADR	0x2327

/*--------------------------------- TARIH/SAAT -----------------------------------*/
#define DW_TARIH_SAAT_PAGE_ENTER_ADR	0x2500
#define DW_FIRST_WRITE_RTC_ADR			0x009C
#define DW_WRITE_RTC_DONE_MSG			0x5AA5
#define DW_FIRST_READ_RTC_ADR			0x0010

/*---------------------------------OTOMATIK ACMA -----------------------------------*/
#define DW_SAAT_IKON_ADDR				0x177A
#define DW_OTOMATIK_ACMA_ENTER_ADR		0x2700
#define DW_OTOMATIK_ACMA_ADR_LENGTH		59

#define DW_OTOTMATIK_GUN_ENTER_ADR		0x1768
#define DW_OTOTMATIK_GUN_EXIT_ADR		0x1778
#define DW_OTOTMATIK_IKON_AKTIF_ADR		0x1779
#define DW_OTOMATIK_ACMA_ISIM_CHOOSE 	0x1767
#define DW_OTOMATIK_ISIM_ROW_ADR		0x176D

#define DW_OTOMATIK_ACMA_ILK_ADR		0x1584
#define DW_OTOMATIK_ACMA_SAAT_ADR		0x1584
#define DW_OTOMATIK_ACMA_MIN_ADR		0x1585
#define DW_OTOMATIK_UST_SICAKLIK_ADR	0x1586
#define DW_OTOMATIK_ALT_SICAKLIK_ADR	0x1587
#define DW_OTOMATIK_BUHAR_ADR			0x1588
#define DW_OTOMATIK_ISIM_ILK_ADR		0x1589
#define DW_OTOMATIK_PISIRME_INFO_ADR	0x1595
#define DW_OTOMATIK_AKTIF_INFO_ADR		0x1597

#define APP_OTOMATIK_ACMA_ILK_ADR		0x1F38

#define APP_OTOMATIK_ACMA_SAAT_ADR			0x1F38
#define APP_OTOMATIK_ACMA_MIN_ADR			0x1F39
#define APP_OTOMATIK_UST_SICAKLIK_ADR		0x1F3A
#define APP_OTOMATIK_ALT_SICAKLIK_ADR		0x1F3B
#define APP_OTOMATIK_BUHAR_ADR				0x1F3C
#define APP_OTOMATIK_PISIRME_INFO_ADR		0x1F3D
#define APP_OTOMATIK_PISIRME_AKTIF_ADR		0x1F3E
#define APP_OTOMATIK_PISIRME_RECETE_NUM_ADR	0x1F3F



#define DW_OTOMATIK_MANUEL_PISIRME		1
#define DW_OTOMATIK_RECETE_PISIRME		2

#endif /* INC_DWIN_ADRESS_H_ */
